"""empty message

Revision ID: 264d14556923
Revises: 2fc7a3f23fb0
Create Date: 2019-02-24 03:13:36.589700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '264d14556923'
down_revision = '2fc7a3f23fb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'device', ['device_lib_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'device', type_='unique')
    # ### end Alembic commands ###
