"""empty message

Revision ID: 3ae91e080d0e
Revises: f0f65ff08148
Create Date: 2019-02-24 03:05:02.464831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ae91e080d0e'
down_revision = 'f0f65ff08148'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registrations',
    sa.Column('asdf', sa.Integer(), nullable=True),
    sa.Column('zxcv', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asdf'], ['pass.id'], ),
    sa.ForeignKeyConstraint(['zxcv'], ['device.id'], )
    )
    op.create_unique_constraint(None, 'device', ['device_lib_id'])
    op.create_unique_constraint(None, 'device', ['id'])
    op.create_unique_constraint(None, 'device', ['push_token'])
    op.create_unique_constraint(None, 'pass', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pass', type_='unique')
    op.drop_constraint(None, 'device', type_='unique')
    op.drop_constraint(None, 'device', type_='unique')
    op.drop_constraint(None, 'device', type_='unique')
    op.drop_table('registrations')
    # ### end Alembic commands ###
