"""empty message

Revision ID: 774b02a2f59c
Revises: 767a59169510
Create Date: 2019-02-19 11:09:57.886909

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '774b02a2f59c'
down_revision = '767a59169510'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('member', 'expiration_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('member', 'member_level',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('member', 'member_level',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('member', 'expiration_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
