"""empty message

Revision ID: 7812f28e1416
Revises: 1718e742d15f
Create Date: 2019-02-24 02:41:26.123498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7812f28e1416'
down_revision = '1718e742d15f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pass_device_association',
    sa.Column('pass_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.ForeignKeyConstraint(['pass_id'], ['pass.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pass_device_association')
    # ### end Alembic commands ###
