"""empty message

Revision ID: 835cd2f99470
Revises: d784ce8cd75c
Create Date: 2019-02-24 02:25:38.155631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '835cd2f99470'
down_revision = 'd784ce8cd75c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pass_device_association',
    sa.Column('pass_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.ForeignKeyConstraint(['pass_id'], ['pass.id'], )
    )
    op.add_column('device', sa.Column('device_lib_id', sa.String(length=100), nullable=True))
    op.add_column('device', sa.Column('push_token', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'push_token')
    op.drop_column('device', 'device_lib_id')
    op.drop_table('pass_device_association')
    # ### end Alembic commands ###
