"""empty message

Revision ID: 856b4db0c9e1
Revises: 3ae91e080d0e
Create Date: 2019-02-24 03:09:04.130999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '856b4db0c9e1'
down_revision = '3ae91e080d0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pass_device_association',
    sa.Column('asdf', sa.Integer(), nullable=True),
    sa.Column('zxcv', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asdf'], ['pass.id'], ),
    sa.ForeignKeyConstraint(['zxcv'], ['device.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pass_device_association')
    # ### end Alembic commands ###
