"""empty message

Revision ID: 9f3b8633dfda
Revises: 856b4db0c9e1
Create Date: 2019-02-24 03:09:57.161750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f3b8633dfda'
down_revision = '856b4db0c9e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pass_device_association',
    sa.Column('pass_id', sa.Integer(), nullable=True),
    sa.Column('device_device_lib_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['device_device_lib_id'], ['device.device_lib_id'], ),
    sa.ForeignKeyConstraint(['pass_id'], ['pass.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pass_device_association')
    # ### end Alembic commands ###
