"""empty message

Revision ID: ac5dd7f1c0e8
Revises: 835cd2f99470
Create Date: 2019-02-24 02:36:40.858721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac5dd7f1c0e8'
down_revision = '835cd2f99470'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pass_device_association',
    sa.Column('pass_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.ForeignKeyConstraint(['pass_id'], ['pass.id'], )
    )
    op.add_column('device', sa.Column('device_lib_id', sa.String(length=100), nullable=True))
    op.add_column('device', sa.Column('push_token', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'push_token')
    op.drop_column('device', 'device_lib_id')
    op.drop_table('pass_device_association')
    # ### end Alembic commands ###
