"""empty message

Revision ID: c9e44c741b1a
Revises: 2df408303723
Create Date: 2019-02-19 19:49:55.104085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9e44c741b1a'
down_revision = '2df408303723'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('device_lib_id', sa.String(length=100), nullable=False),
    sa.Column('push_token', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('device_lib_id')
    )
    op.create_table('registrations',
    sa.Column('device_device_lib_id', sa.String(length=100), nullable=False),
    sa.Column('pass_serial_number', sa.String(length=100), nullable=False),
    sa.Column('pass_pass_type_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['device_device_lib_id'], ['device.device_lib_id'], ),
    sa.ForeignKeyConstraint(['pass_pass_type_id'], ['pass.pass_type_id'], ),
    sa.ForeignKeyConstraint(['pass_serial_number'], ['pass.serial_number'], ),
    sa.PrimaryKeyConstraint('device_device_lib_id', 'pass_serial_number', 'pass_pass_type_id')
    )
    op.add_column('pass', sa.Column('last_updated', sa.DateTime(), nullable=True))
    op.add_column('pass', sa.Column('pass_type_id', sa.String(length=100), nullable=False))
    op.add_column('pass', sa.Column('serial_number', sa.String(length=100), nullable=False))
    op.alter_column('pass', 'file_name',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_column('pass', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pass', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.alter_column('pass', 'file_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
    op.drop_column('pass', 'serial_number')
    op.drop_column('pass', 'pass_type_id')
    op.drop_column('pass', 'last_updated')
    op.drop_table('registrations')
    op.drop_table('device')
    # ### end Alembic commands ###
