"""empty message

Revision ID: cba2ee16048f
Revises: 9e1bd4c02006
Create Date: 2019-02-19 11:38:18.430159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cba2ee16048f'
down_revision = '9e1bd4c02006'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('member', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100))
    op.alter_column('pass', 'member_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pass', 'member_id',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('member', 'id',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER())
    # ### end Alembic commands ###
