branch-defaults:
  default:
    environment: Iosflask-env
global:
  application_name: flaskapi
  branch: null
  default_ec2_keyname: killafter-george-nvidia-key-2018-10-06
  default_platform: python-3.6
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
